ur5e:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  ur5e_id_controller:
   type: effort_controllers/JointGroupEffortController
   joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

